name: Continuous Integration

on:
  push: 
    branches:
     - feature/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -  name: Checkout
         uses: actions/checkout@v5
         name: Build da aplicação
         run: mvn clean package
         