name: Continuous Integration

on:
  push:

jobs:
  build_and_pull:
    runs-on: ubuntu-latest
    steps:
      -  name: Checkout
         uses: actions/checkoutv@5
      -  name: Login to Docker Hub
         uses: docker/login-action@4
         with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}