on:
  push:

jobs:
  demo1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Olá, mundo!"
      - name: step2
        run: echo "Mensagem 2"
      - name: step3
        run: echo "Mensagem 3"